# --- CORE SITE METADATA ---
site_name: Solvya Skin  - Handcrafted Papaya & Milk Soap
# In mkdocs.yml
site_url: https://solvyaskin.github.io/solvya/
site_description: Discover Solvya Skin's Papaya & Milk Gentle Renew Soap, a handcrafted, natural skincare solution from the Philippines. Perfect for sensitive skin, our soap is made in small batches, combining heritage and gentle care to reveal your true glow.
site_author: Solvya Skin

# --- OPTIONAL REPOSITORY LINKS (Update or remove) ---
repo_name: solvyaskin/solvya
repo_url: https://github.com/solvyaskin/solvya

# --- FOOTER ---
copyright: Copyright &copy; 2025 Solvya Skin. All rights reserved.

# --- THEME CONFIGURATION ---
theme:
  name: material
  language: en
  favicon: assets/solvya_favicon.png
  logo: assets/solvya_favicon.png
  palette:
    primary: white
    accent: white
    scheme: default
  features:
    - navigation.search
    - navigation.toc
  font:
    text: Google Sans

# --- EXTRA ASSETS ---
extra_css:
  - stylesheets/extra.css





# --- EXTRA METADATA & SOCIAL LINKS ---
extra:
  generator: false # Disables the "Made with Material for MkDocs" footer text
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
      name: Mastodon
    - icon: fontawesome/solid/paper-plane
      link: mailto:<email-address>
      name: Email
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/aitrends.now
      name: TrendingNow on Instagram

# --- NAVIGATION MENU ---
nav:
  - Handcrafted Papaya & Milk Soap: index.md
  - Contact: contact.md
  - About Us: about.md
  - Order Now: order.md

# --- MARKDOWN EXTENSIONS ---
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

# --- PLUGINS ---
plugins:
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
  - git-revision-date
  - social:
      cards: false